#include <bits/stdc++.h>

using namespace std;


// O(n^2)
int numSplits(string s) {
    set<char> left, right;
    int cont = 0;
    for(int i = 0; i < s.size() - 1; ++i) {
        left.insert(s[i]);
        right.insert(s.begin() + i + 1, s.end());
        if(left.size() == right.size())
            cont++;

        right.clear();

    }
    return cont;
    
}


// O(n)
int numSplits_2(string s) {
    int cont = 0;
    unordered_set<int> left, right;
    vector<int> pref(s.length(), 0), suff(s.length(), 0);
    int l = s.size();

    for(int i=0;i < l; ++i){
        left.insert(s[i]);
        right.insert(s[l - i - 1]);
        pref[i] = left.size();
        suff[l - i - 1] = left.size();
    }

    for(int i = 1; i< l; ++i) {
        cont += (pref[i-1] == suff[i]);
    }

    

    return cont;
}


int main() {
    string s = "aceceaacececaecaeaabaacbaceddccbdbddcdbededcabcbaaddbdadcaaccaccededeadebbaeeebdaccebbceddddedeaaaaabcdbebecdaaabdbdcebbbbabaeccadbcaceeadabcccbcbeabdadaedabaaeeeddebeaddecabedceaaebceaaccbcdedcaacedceaaddaebaceaeaedeeaaccdebdcccbaedebebacdbaedabeceadaeeeddbdaacebaabeebcbaaaeeccedcaabbeddcadbddcddbadccaeecbdddebdabecadcdaccdcbcbbbabcbdddadeabbcbccebbbebbabbbbeebebadabcbaeadabadbbababdcbadbbaabeabecdeabeddabbbdbcdccddadacabedaeccaabaebceaceabececcdbbacdabdbbaeaeeccbcceaababbeccaeebcedcceabceaddcedeebcebbebcdcaaddccbaacebabdabcceecbbcdeebacaaaecbdaaddaadabddacecdcddcceecddcededadacabdeadebbbcdccacabcebdebbbeacaacbeebcddabeaedaddcbadcbcbcadebebcacaeebbadbdcdceedbaabecabbeedebdabcbacabeadddcababebedabcacacadcaeeacbabecbdadecacabdebebbdeeeccecececabdeceeacdbddcdddebaeeddcaddecbebabdeedacddecccbccdbedecacbbebccccebbadcaeaeccedcaaeeaddabedcebedbcaeeaabacbbcadcadeeeaacbececcbdeeceecaaddcebbbeacacddedaabdeabddeccacebdccbdedbddccadbdddaabdebbbacaacabeacedcdedbeeadbdcacbbbebabecabacdceeedabaeabdbbdeeaadcdadcdaccccbabcbbdaaebcbdbcdccdcebbbebbddbaaeeabebebaeaaddaabccaeeeeeedebbccaccdedcebdaadddcccaceaeacecbeecddeeaeceedcdcacddabeaadcccabaebacebebceecebbdededaacbcbdeacabcedccecbdcedcdaecedbadaaecbbdeebccecddbcbaaabbddccbdacddcadebadacdccaeabddacdceabbdcccabaaaabeaecddbaeceacdadacdeebcedccbbdaadbcbbeadbacaedeebaebdacabcdbacabebbadacdadecabbeebceaddbbbdbbddbcdbcdebaecccdbcbacceddebceceecabcdbaacecbbdbccbabeabaabdaebebbaaeabedaaedbbaeeaacebbcddcadccbdbbeedadadedeeaaedcdeeccecedbbaeddbecaaadeeaeadcaacecceedcabddcacbebebbbaeaccadeedcaddbeedcdbdbabdabccbdaeebbadbaaccedbabcedcbebceadaebdaeecabccaecddbcadaaebeadacddcadcabcbdecaeccbddedbccbdabbcbccaeaeabcbdeecabcbbeaddecdaeccbceceeebccdccdaeaabcceaeaacdcacadacdceaeceeeeaceabbecbbcaceddacebdcbebeabcdbddceeabacbecbecbebdecbabeeadacbdadbbebaaebacecbadbbdbabebecdbecdebbebcaccdddccebbbcbcecbcaeaeedaaddcaedcacebdcdaabdebadcbdaaeeedaaacdeabbdbeedcebaaecadeeadbeabecdeeaadcccaaeedaecddedbeabcacadceecbdacabdbdeebacadeaeccbbaabebdeadabecbdabeaacbebcedebbacaebcaeeccdbceeaedbceacaadbaddeabcdadedaceecbebcdbcbdacdccbaeaecbbeddcaccbebddecceaaacaeeeabbccbebcdeceedaddaceecccaaeaecdedcacbcdeaecaaeedacaebadaebacaccdddebeddacbdeeeaeccacbeacebacccaeedaacaecccabaadcdceeadbcccdbeecabacdaabcbabeeacddeddbcbbdeadaabbccddeacecbebeeeebdadaaddecddbcbcbadeedadcdadbbdedcadbbabbcecdbcebcabbbedbadcdecdedeedbcbbeaabecaadacebebcbeccaeacbbbecabeaebabaeaeacdeabebcbdbdacdbbedacedacdbaeaebeccbdcececbddacaedebeabcebdbaecccdcecddbecbadbacbabcecddadecabbbdcccaeeadcceaebacdbcaddbbbcbbbcacbbcbdddcdcdbdddccabbabdedadcddcbddbbebacddceeaaebdecebbaacdbcedbaaccbcdacdeccaccacadbabdadaceccbcdaccacdccdbcbaabcaddbbdcbcadaeededabdebeadbaabdebcbedacaecdbdcaddddeeaecdaeeadacbecbceccebedbabbbdddcbdcbbadccbabadabecaaeeaddcaaaeebecdbbdcbbbeacdaadacbababdecccedddbebebaaadaccbcbdacbbaabdeddaeacddcebddcecdecbcaabddaccecacbbacbbeabeebcdbeadebeaedebbcabcceedbccbaeeebccabddaedbecabbbedbccadeadaeeecacbecdbdccaabadbdcacabadacdcaeaabbccccedebdceecbdaedaebecccaeaaecadbdbaebcbcdeddabbcebbaccadceaecadabeebeccecbebccacadcacbcebbaaccbecdabcaeeecdeccddedbbabccaceaceacbbbedddeadebddedbbaacababdcadbcceaadeceecaeebaabddeecdbcaccecabbaecdaeebaededdcdaadadaeebebaaecddeeebceedbaddcdacebacbbececedabbeeebaeeccbcbedbbcdedcdbdbccaddaddbeeadbcbcecadaedadaedabcbdaaabadccabdbdeddaaccecabaaeaaeeeacceecdabbdaaceaadbeccbbbeabbaeededaccadabdaabebbbabdbabeedbcbaabeeebadbbeceeaecccdceccaadcdabedebbedbbbbaedbcdabababbbddccbaaeddbaababedeaeecbdcacdebebaceeecdbdaadcceacbdcddadcaaaabaaebceeeaccddecccecebaaeddbecbeedebbbbcbaddaebcdeaebbaeaaaeabcabaacdaeaacdedcbeaeadbadeeebddbcdecccdedcdbaaedeeabadebdaacebbdadcabebcddacbabdebdadcbdbccccbccbbdacebdedbabddadbbaebcbedcbedcacdecccdadeadadecdbcceddececeaeabbbbbbdabaeadaceabbebeddbacbadceeccbaabdeaeaebddebdcbeeddeaebdabdadddaecaaacbdabdedadaecabceaeaebcdbebdcbdcedcebddeacbbabeaaabdeccddcbeddccddccaeddbbcbadbceadcbcdebddcbcededdbebbbacdbaaaabeeebbbecbabbdaedbedacbabaebbbdddaadedcccbebacecdadcceabddbbacaecedceadbaeacaeedaebcdaceeeddbbadadacbcddbbcdebeacabdaccaaccccecceaccbeaedaebbebabecaaabcacadccebaadceeddbaadeacacacbaeeecccebeaeeeccabbeebbaeccdbaacdcdeeeacadcdedacecbcdbdebceebcddeedecccbbbedcdadcaebabbbcbaaeabdbdbdabaeedeccebdbbdceccaddaccceabecdaebbbddcccdcadaacaaeecbbdbabececdacedaebcabdeebbbebebbcadcabcdebaaeabecdbbabddecaddddbbcaaacaeaadecdbeaaaeedceaacaadeeebcdacbcecaceccadaaceabeabeeeaacbcbcdceeacadeebbbdccceaabaabababcbebaacbbdccbccbdccadaaeeabecbbeebdecdddcecacdcdadbeeeaaeeaeeaacbbdcdaaddbaeaacabdaedcacedcacdcbebedaebcbdcaceabdacacbbdebabcbdebeadecaaebceabecbdeeddaababdebaddadcaaeeecbeaeaaaadedebdbbabcdacbbecebdaaccbbbdcaeecdccaddebdbbcbebcdbeccdaceecdedaaebdaebbcccdaddebbcbaebaeacacceddedcdccacacaaaeabccbcdebecbdacdbeacadcacaeecccdbbeccadceaddabdaabaabddabceadddcacbacdebceebdceedaeddebdbceebeaaeceecaeabddddbccbcadbdbcdabdcadbacccabbddaacadebddedddaecbbeeecebddacaaaceaddcaddadeccddbaedaacadeabaddbaabddbedecbeeeeceedadabdeebdddaebcdedbeccabcbbedacdaaeabcacaabdbaeeeaebeddddbababaeeeadbbaddaebccbdeeedbbacedcbcbabcdabdebcedddcedddedcabadbaedbbbdbcbabeeebecebcecedeaccadcabaaaedeceeecacebaaadccbcecbedebdbdcebaecebbedceaeaeccbedccecceadccbbbacbddbcecbbcebcaadddcaceedbadcbdacedaddcbeabbaaceddaeaabceccbbacacdddeeeadcbdcdbcdaeceaedbcecdcaecdaccaabdaacbadbacccacdbacbbcadabbeabcdceabaacaceadccbcaeadaabaebdcdcbacdcaadeccabdeebcecaedbddeacbcdbbbdbbedccbdacbacddabeeabbdeccdeaedbeeebadbdddbebeecbcbdcceeebabacccbbbbcecadacabdcacbadccaaaaadabeeeecdccdaeededbdeadebecebbcabcdaddbbbcccabadbbabdeabecaaaadaeebacacbebecbeeaacbdbceecaaeabadbcdcdbcdeacacebdedecadaecaaacbebccacaeaaebbbecbabcccaddbcdaeedddabaeaedbbdecdcaeeddccbacbccbdbabdabacddabcadbbceeebeaccbaacacbabcdaaccbcccdbcecbacecbccdbcbcbcdebbecaebcdcbcbccdadadceebcdeebdcdcbcdabccccadcabbcbadaedaaeadbeebaaccaadbcbceedbdedbbcacaeeecaceadecececeaedebbdacdbbeebdbcdbbbabdccaaecbdaebbcaeaadbddebeaccbceabdbaccbabedcdbbedadbaccbbaccecdcabcccbaacbceabbeebaeaadbdabebcbddcbaedadeedeabebaaabcacbddccabebbccaabecccbdbededecebdbdeedeccceddcceeeeccecdadeeedabcceddccbbdddcdacacaddddaeaeaccacbecaeddeddcdbbdddecddedadcacdccbaeedbbedeaebdbdaeebcddaccbbedeceeccbeecadcbccdbcabadacdedbaceaeeaebadcbbbbeeddedbebbeadceedccabddcddceebbaddeadeeeedabeaaadbcceebaeeddedceeadabcbbacdcedbdbcbeeeaedbacdeaddbadbdceedeecddeeaebbdedeeebaececcedcabdadecbbcaccebeeccaeaebadaecaaeadadaeaacadebabeecdeedaaeabbdadeacdcaedebbdcccceadaecccbabbaadebcdcbceddecdddaaeadabbeebdbdaaaaedecbcedeaceabcbccbdadeedaebaabcaddeececabceddbcadbdddcdbbbeeaedcadaabbcedaaccdbbaacedbbcacbdddbdbaebdbcbaebaebabecbebaedabebdecdddccdeeedebecaaeceaeacdbbbdceaeaacebaccecacdeaadbdaaddebeadbacdcaabcaddedcccceeccdacbdadaedcdebadeddaadbedaacdadddebbeeddcdcaccecbcbabbbdeeecacedceacbaaacdbdeececccdbdceeeadbabdccaabdbacebeabdbddcadbbacacdebcceccecbdcbabbccbbcbeabdcbaceabaceaeeadaeccdaedeaabaeddbaadcbabccaccdabdcdbecccbbbdaccdcacaadccdbeaeceedabdbaeaebcdacebcadeaecdcbbcbedabdaadebeecebabccebdaaebacdabadaedadcbdebdadacadaeadbabeeceadeeeabaaddacaeebdebcbddeaecabedbedaceccbeacccdeedbeacccabdbdaecdbddeedbdbcbacaaacdcdbaccacecacdedddeeadcbbabccabdbbeabacccdceaaabebabbecdaecdbbbddcebbedcebbdaeaeabadaeddeeeedddaaccccabaaaebcbcddacaaaadebdcecbccaaaaebaebdbdbaadcacadcbeecbdaccbdddbdbcaccacdeacbcbcabcdbdebaaaeaeaabeecbbebcdeebebaeeeabeebdbdcbcaeceaadcdbadeadceaedbeecedbcacbbecddcebacdedcbddcaccaabaedabeceaccddbddadcedceddbcbedcabaddbebadeadbcbedcbaacebdceacadeeeadbeeceeaaebceecaccccedcbbadbbadedeaaebceaedaacbccdabdbcabbebeaddeeecababddabdeacecaddabeaecaededcecdbaeadccbceecbddbbdbbecbbbbdcbedcaeeadceeebcedcbedbdccbebedbaebbcebdbacccababbaaadeccbaeddbebbdecdbbcadeaeeaeabcccbdaceedadadcadcaccddebecbedecdabcbcdebbdcdcebbaebddedbdeccaeacbeeebaeaeeebbadcddebacbabdeadccdbccedddcaccceecbeadaeccccedcdadabdcdaeceeeccebaeebecdddeeaaabdcbceebccaccbacdeabbedbccedcaedebedbcacdedbcedcedaeeaeeaeebbebbedbcedcaebbeaeeecebebaecbdeabedbdabccdd";
    cout<<numSplits_2(s);
    

    return 0;
}